#!/usr/bin/env python3

import ping_multi_ext.main

def parse_argv():
    parser = ping_multi_ext.main.argv_parser_base(
        'Execute multiple external ping commands at once.'
    )

    # non-required first

    dval = 1
    parser.add_argument('--timeout', type=float, default=dval,
        help=f'ping reply timeout in seconds; default={dval}')

    # required

    parser.add_argument('--ping', nargs=2, metavar=('UNIQUE_NAME', 'COMMAND'),
        action='append', required=True,
        help='each command must be specified by an arbitrary unique name and the command itself; ' +\
             'you can specify this option many times'
    )

    return parser.parse_args()

ping_multi_ext.main.main(parse_argv())
